language: php
php:
  - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'
  - hhvm
  - nightly

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3
  - wget http://goo.gl/qTy1IB -O selenium-server-standalone.jar
  - java -jar selenium-server-standalone.jar &
  - composer self-update
  - composer install

script:
  - vendor/bin/phpunit
